package: spectralDNS

user: spectralDNS

platform:
  - linux-64

engine:
  - python=2.7

install:
  - conda config --set always_yes true
  - conda update -q conda
  - conda config --add channels spectralDNS
  - conda config --add channels mikaem/label/dev
  - conda build conf/conda
