# http://travis-ci.org/spectralDNS/spectralDNS

language: python
python:
    - "2.6"
    - "2.7"
    
branches:
  only:
    - master

cache:
  apt: true

before_install:
    - sudo apt-get update -q

install:
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION Cython mpi4py scipy pytest sympy
    - wget https://github.com/spectralDNS/mpiFFT4py/archive/1.0.tar.gz
    - tar -xzvf 1.0.tar.gz
    - cd mpiFFT4py-1.0 && python setup.py install -- && cd ..
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        export PYTHONPATH="$HOME/miniconda/lib/python2.7/site-packages:$PYTHONPATH"
      else
        export PYTHONPATH="$HOME/miniconda/lib/python2.6/site-packages:$PYTHONPATH"
      fi
    #- git clone git@github.com:spectralDNS/mpiFFT4py.git
    #- cd mpiFFT4py && python setup.py install && cd ..
    - source activate test-environment
    - python setup.py install
    - which python
    
script: cd $PWD/tests; py.test

#notifications:
#  email: false
