# http://travis-ci.org/spectralDNS/spectralDNS

language: python

python:
    - 2.7
    
branches:
  only:
    - master

sudo: false

install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda config --add channels conda-forge
    - conda config --add channels spectralDNS
    - conda create -q -n test-environment pip pyfftw mpi4py scipy pytest cython sympy h5py-parallel
    - source activate test-environment
    - pip install mpiFFT4py nodepy
    - python setup.py install
    
script: cd $PWD/tests; py.test

#notifications:
#  email: false
