# http://travis-ci.org/spectralDNS/spectralDNS

language: generic

os: osx
osx_image: xcode7.2

sudo: False

env:
  matrix:
    - CONDA_PY=27
    - CONDA_PY=34

before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b
      source /Users/travis/miniconda3/bin/activate root
      conda config --set show_channel_urls true --set always_yes yes
      conda info -a
      conda install conda-build
      conda env create -f tests/test-environment.yml

script:
  - source activate spectralDNS
  - conda build conf/conda
