package:
  name: spectraldns
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: ../../

build:
  number: 34

requirements:

  build:
    - toolchain  # [osx]
    - python
    - cython
    - numpy
    - nomkl
    - fftw
    - pyfftw
    - mpi4py
    - scipy
    - pip
    - pytest-runner

  run:
    - python
    - numpy
    - nomkl
    - cython
    - fftw
    - hdf5-parallel
    - h5py-parallel
    - mpi4py
    - scipy
    - sympy
    - pyfftw

test:
  source_files:
    - tests

  imports:
    - spectralDNS
    - nodepy
    - mpi4py_fft

  requires:
    - pytest
