package:
  name: spectraldns
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: ../../

build:
  number: 35

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - cython
    - numpy 1.16.*
    - setuptools
    - nomkl
    - fftw
    - pyfftw
    - mpi4py
    - mpi4py-fft
    - {{ mpi }}
    - scipy
    - pytest-runner
    - pythran
    - pip

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - nomkl
    - cython
    - fftw
    - {{ mpi }}
    - hdf5 * mpi_{{ mpi }}_*
    - h5py * mpi_{{ mpi }}_*
    - mpi4py-fft
    - mpi4py
    - scipy
    - sympy
    - pyfftw
    - pythran
    - pip

test:
  source_files:
    - tests

  imports:
    - spectralDNS
    - shenfun

  requires:
    - pytest
