package:
  name: spectraldns
  version: "1.0"
  
source:
  git_url: ../../  
  
build:
  number: 14

requirements:
  build:
    - toolchain #[osx]
    - python
    - cython
    - numpy
    - hdf5-parallel
    - h5py-parallel
    - pyfftw

  run:
    - python
    - numpy
    - hdf5-parallel
    - h5py-parallel
    - mpi4py
    - mpifft4py
    - sympy
    - nodepy
    - pyfftw

test:
    requires:
      - python
      - pytest
