package:
  name: spectraldns
  version: "1.0"
  
source:
  git_url: ../../  
  
build:
  number: 2

requirements:
  build:
    - python
    - cython
    - numpy
    - h5py ==2.6.0

  run:
    - python
    - numpy
    - h5py ==2.6.0
    - mpi4py
    - mpifft4py
    - sympy

test:
    requires:
      - python
      - pytest
      - h5py ==2.6.0
      - mpi4py
      - mpifft4py
      - sympy
