package:
  name: spectraldns
  version: "1.0"
  
source:
  git_url: ../../  
  
build:
  number: 14

requirements:

  build:
    - toolchain #[osx]
    - python
    - pip
    - cython
    - numpy
    - hdf5-parallel
    - h5py-parallel
    - pyfftw

  run:
    - python
    - numpy
    - hdf5-parallel
    - h5py-parallel
    - mpi4py
    - scipy
    #- mpifft4py
    - sympy
    #- nodepy
    - pyfftw

test:
  imports:
    - mpiFFT4py
    - nodepy
    - spectralDNS

  requires:
    - python
    - pytest
