package:
  name: spectraldns
  version: "1.0"
  
source:
  git_url: ../../  
  
build:
  number: 15

requirements:

  build:
    - toolchain #[osx]
    - python
    - pip
    - cython
    - numpy
    - hdf5-parallel
    - h5py-parallel
    - pyfftw

  run:
    - python
    - numpy
    - hdf5-parallel
    - h5py-parallel
    - mpi4py
    - scipy
    #- mpifft4py
    - sympy
    #- nodepy
    - pyfftw

#test:
  ##imports:
    ##- spectralDNS
    ##- nodepy
    ##- mpiFFT4py

  #requires:
    #- python
    #- pytest
