package:
  name: spectraldns
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: ../../

build:
  number: 37

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - cython
    - numpy >=1.14.*
    - setuptools
    - {{ mpi }}
    - pytest-runner
    - pip

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - hdf5 * mpi_{{ mpi }}_*
    - h5py * mpi_{{ mpi }}_*
    - shenfun >=2.2.2
    - mpi4py-fft >=2.0.3
    - mpi4py
    - scipy
    - sympy

test:
  source_files:
    - tests

  imports:
    - spectralDNS
    - shenfun

  requires:
    - pytest
