package:
  name: spectraldns
  version: "1.0"

source:
  git_url: ../../

build:
  number: 26

requirements:

  build:
    - toolchain  # [osx]
    - python
    - cython
    - numpy
    - pip
    - pytest-runner

  run:
    - python
    - numpy
    - cython
    - hdf5-parallel
    - h5py-parallel
    - mpi4py
    - scipy
    - sympy
    - pyfftw

test:
  source_files:
    - tests

  imports:
    - spectralDNS
    - nodepy
    - mpiFFT4py

  requires:
    - pytest
