package:
  name: spectraldns
  version: "1.0"
  
source:
  git_url: ../../  
  
build:
  number: 4

requirements:
  build:
    - python
    - cython
    - numpy
    - gcc
    - hdf5 ==1.8.14
    - h5py ==2.6.0

  run:
    - python
    - numpy
    - hdf5 ==1.8.14
    - h5py ==2.6.0
    - mpi4py
    - mpifft4py
    - sympy

test:
    requires:
      - python
      - pytest
