{% set data = load_setup_py_data() %}

package:
  name: spectraldns
  version: {{ data.get('version') }}

source:
  git_url: ../../

build:
  number: 0

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - cython
    - numpy
    - setuptools
    - {{ mpi }}
    - pytest-runner
    - pip

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - hdf5 * mpi_{{ mpi }}_*
    - h5py * mpi_{{ mpi }}_*
    - shenfun >=3.2.0
    - mpi4py-fft >=2.0.3
    - mpi4py
    - scipy
    - sympy

test:
  source_files:
    - tests

  imports:
    - spectralDNS
    - shenfun

  requires:
    - pytest
