package:
  name: spectraldns
  version: "1.0"
  
source:
  git_url: ../../  
  
build:
  number: 18

requirements:

  build:
    - toolchain  # [osx]
    - python
    - cython
    - numpy
    - mpi4py

  run:
    - python
    - numpy
    - cython
    - hdf5-parallel
    - h5py-parallel
    - mpi4py
    - scipy
    - sympy
    - pyfftw

test:
  imports:
    - spectralDNS
    - nodepy
    - mpiFFT4py

  requires:
    - pytest
