package:
  name: spectraldns
  version: "1.0"
  
source:
  git_url: ../../  
  
build:
  number: 2

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy
    - scipy
    - mpi4py
    - mpifft4py
    - sympy

test:
    requires:
      - python
      - numpy
      - scipy
      - pytest
